import type { Movie } from './types';

export const movies: Omit<Movie, 'posterUrl'>[] = [
  {
    id: 'inception',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genre: 'Sci-Fi',
    rating: 8.8,
    year: 2010,
  },
  {
    id: 'the-dark-knight',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genre: 'Action',
    rating: 9.0,
    year: 2008,
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    genre: 'Sci-Fi',
    rating: 8.6,
    year: 2014,
  },
  {
    id: 'parasite',
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genre: 'Thriller',
    rating: 8.6,
    year: 2019,
  },
  {
    id: 'the-matrix',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genre: 'Sci-Fi',
    rating: 8.7,
    year: 1999,
  },
  {
    id: 'joker',
    title: 'Joker',
    description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
    genre: 'Drama',
    rating: 8.4,
    year: 2019,
  },
  {
    id: 'avengers-endgame',
    title: 'Avengers: Endgame',
    description: 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers must assemble to reverse Thanos\' actions.',
    genre: 'Action',
    rating: 8.4,
    year: 2019,
  },
  {
    id: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    genre: 'Sci-Fi',
    rating: 8.0,
    year: 2017,
  },
  {
    id: 'mad-max-fury-road',
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    genre: 'Action',
    rating: 8.1,
    year: 2015,
  },
  {
    id: 'pulp-fiction',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genre: 'Crime',
    rating: 8.9,
    year: 1994,
  },
  {
    id: 'the-grand-budapest-hotel',
    title: 'The Grand Budapest Hotel',
    description: 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    genre: 'Comedy',
    rating: 8.1,
    year: 2014,
  },
  {
    id: 'spider-man-into-the-spider-verse',
    title: 'Spider-Man: Into the Spider-Verse',
    description: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    genre: 'Animation',
    rating: 8.4,
    year: 2018,
  },
  {
    id: 'arrival',
    title: 'Arrival',
    description: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    genre: 'Sci-Fi',
    rating: 7.9,
    year: 2016,
  },
  {
    id: 'la-la-land',
    title: 'La La Land',
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    genre: 'Musical',
    rating: 8.0,
    year: 2016,
  },
  {
    id: 'get-out',
    title: 'Get Out',
    description: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
    genre: 'Horror',
    rating: 7.7,
    year: 2017,
  }
];
